services:
  # backend-graphql:
  #   container_name: backend-graphql
  #   build:
  #     dockerfile: ./apps/backend-graphql/Dockerfile
  #   restart: on-failure
  #   environment:
  #     - BACKEND_PORT=3100
  #   depends_on:
  #     - postgres
  #     - redis
  #   ports:
  #     - 3100:3100
  #   volumes:
  #     - ./apps/backend-graphql:/app/backend-graphql

  # frontend-react:
  #   container_name: frontend-react
  #   build:
  #     context: .
  #     dockerfile: apps/frontend-react/frontend-react.Dockerfile
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./apps/frontend-react:/app/frontend-react

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
